### ISSUE TITLE
ibmclose no longer accessible via data()

### ISSUE THREAD

**Issue by GeoBosh** [robjhyndman/fma#6]
In a yet unpublished package, I have checks using the `ibmclose` data with something like
```
data(ibmclose, package = "fma") # ibm data from BJ
```
In `fma` version 2.4, released recently, this no longer works. 

Is this deliberate?  I can see that `fma::ibmclose` works in v2.4 and in v2.3 (and presumably in older versions of 'fma'), so could use that instead.

**Comment by robjhyndman** [comment]
It's not a change in `fma`. Perhaps `data()` has changed. In any case, use `fma::ibmclose` as it avoids creating a new object in the workspace.

**Comment by GeoBosh** [comment]
For the checks it is indeed better to use the qualified `fma::ibmclose` but, FWIW, the error is also in examples and vignettes. In a fresh recent R-devel session:
```
data(ibmclose, package = "fma")  # for `ibmclose'
## Warning message:
## In data(ibmclose, package = "fma") : data set ‘ibmclose’ not found
```
Anyway, I am changing it everywhere. 

PS It doesn't seem to be a change in `data()`.

**Comment by GeoBosh** [comment]
Comparing to v2.3, most datasets in "fma" have been removed from data/. So some are accessible with `data()` and others aren't. It would be nice to be able again to use `data()` for consistency and also because it doesn't load the package.

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/fma/commit/7903ab59b5fdae0f1fb6ac40ac0c712780685815
