### ISSUE TITLE
Dataset motel is missing the variable CPI

### ISSUE THREAD

**Issue by silvialiverani** [robjhyndman/fma#7]
Hello, 
The dataset motel is missing the variable CPI, although it is still described in the helpfile. Would it be possible to add it back in? 

I use this dataset for teaching - thank you very much for this very useful package!

**Comment by robjhyndman** [comment]
The data set is available as cpimel. I'll fix the help file.

---------------------------------------
*Rob J Hyndman*
robjhyndman.com
