### ISSUE TITLE
Sheep Population Units in fma:sheep

### ISSUE THREAD

**Issue by ykinakin** [robjhyndman/fma#9]
The README for the fma:sheep dataset suggests that the values in the time series are given in _millions_ of sheep, however, the data in the time series are all >1000. This implies that the sheep population in England is greater than a billion. Are the data actually given in  _ten of thousands_? A quick search suggests that the sheep population in England in 1860 was closer to 28 million than 2.2 billion (https://www.jstor.org/stable/142206).

**Comment by robjhyndman** [comment]
You're right. The data are originally from Kendall (1976), and I just checked there, and the units should be 10,000. I've now scaled them appropriately in https://github.com/robjhyndman/fma/commit/1a1b76cdb94ae071a43ace6eece188d57c604c72

**Comment by ykinakin** [comment]
Great - thanks very much!
